[package]
name = "themey"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
clap_complete = "4.5.61"
colored_text = "0.3.0"
dialoguer = "0.12.0"
git2 = "0.20.2"
indicatif = "0.18.3"
serde = "1.0.228"
term_size = "0.3.2"
toml = "0.9.8"
