[package]
name = "themey"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
colored_text = "0.3.0"
git2 = "0.20.2"
serde = "1.0.228"
toml = "0.9.8"
